services:
  app:
    build: .
    env_file: docker-compose.env
    ports:
      - "8700:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 10s
